### ISSUE TITLE
Unable to run SimpleBlockingClient and Server

### ISSUE THREAD

**Issue by karthikrsubs** [marianobarrios/tls-channel#89]
Dear Marian, 
While we are trying to run SimpleBlockingClient ,we are getting error in server at read method.

Exception in thread "main" tlschannel.TlsChannelCallbackException: SSLEngine creation callback failed
    at tlschannel.ServerTlsChannel.initEngine(ServerTlsChannel.java:350)
    at tlschannel.ServerTlsChannel.read(ServerTlsChannel.java:262)
    at tlschannel.ServerTlsChannel.read(ServerTlsChannel.java:272)
    at tlschannel.ServerTlsChannel.read(ServerTlsChannel.java:277)
    at tlschannel.example.SimpleBlockingServer.main(SimpleBlockingServer.java:50)
Caused by: java.lang.IllegalStateException: SSLContextImpl is not initialized
    at sun.security.ssl.SSLContextImpl.engineCreateSSLEngine(SSLContextImpl.java:191)
    at javax.net.ssl.SSLContext.createSSLEngine(SSLContext.java:329)
    at tlschannel.ServerTlsChannel.defaultSSLEngineFactory(ServerTlsChannel.java:88)
    at tlschannel.ServerTlsChannel.access$1(ServerTlsChannel.java:87)
    at tlschannel.ServerTlsChannel.initEngine(ServerTlsChannel.java:347)
    ... 4 more

**Comment by marianobarrios** [comment]
Hi Karthik, I would need the code that generates that error in order to help...
